---
# Playbook for installing integration

#############################################################
# Setup headnode
#############################################################
- hosts: headnode
  vars_files:
    - ../config/vars.yml
    - ../StatusDb/config/vars.yml
    - ../Metadata/config/vars.yml
    - config/vars.yml
  roles:
    - headnode
    - lib

#############################################################
# Setup manager
#############################################################
- hosts: manager
  vars_files:
    - ../config/vars.yml # global variables
    - ../StatusDb/config/vars.yml # status-db
    - ../Metadata/config/vars.yml
    - config/vars.yml    # integration specific
  roles:
    - manager
