---
- name: Ensure clean start
  become: yes
  file:
    path: "{{ comp_dir }}"
    state: absent

- name: Directory for Component integration
  become: yes
  file:
    path: "{{ comp_dir }}"
    state: directory
    owner: "{{ datalake_admin_user }}"
    group: "{{ datalake_admin_user }}"
    mode: 0755

- name: Create config dir and copy vars.yml file
  synchronize:
    src: "config"
    dest: "{{ comp_dir }}"
    recursive: yes
    perms: yes

# Copy template for this integration (jdbc/kafka) from common templates
- name: Add configuration script
  template:
    src: "{{ datalake_dir }}/base/roles/headnode/files/lib/templates/jdbc_config.sh.j2"
    dest: "{{ comp_dir }}/config/config.sh"
    mode: 0755

- name: Create log dir
  become: yes
  file:
      path: "{{ datalake_log_dir }}/{{ comp_name }}"
      state: directory
      owner: "{{ datalake_admin_user }}"
      group: "{{ datalake_admin_user }}"
      mode: 0700
