---
- name: Directory for Component integration
  become: yes
  file:
    path: "{{ comp_dir }}"
    state: directory
    owner: "{{ datalake_admin_user }}"
    group: "{{ datalake_admin_user }}"
    mode: 0755
