- name: Create component dir
  file:
    path: "{{ comp_dir }}"
    state: directory
    owner: "{{ admin_name }}"
    group: "{{ admin_name }}"
    mode: 0755
  
- name: Create config dir
  file:
    path: "{{ comp_dir }}/config"
    state: directory
    owner: "{{ admin_name }}"
    group: "{{ admin_name }}"
    mode: 0755

- name: Create log dir
  file:
      path: "{{ datalake_log_dir }}/{{ comp_name }}"
      state: directory
      owner: "{{ admin_name }}"
      group: "{{ admin_name }}"
      mode: 0700

- name: Add application properties
  template:
    src: application.properties.j2
    dest: "{{ comp_dir }}/config/application.properties"
  notify: Restart ca

- name: Install prequisites for the maven_artifact module (pip)
  package: 
    name:  python-pip 
    state: latest

- name: Install prequisites for the maven_artifact module (lxml)
  pip:
    name: lxml

- name: Download application from Artifactory
  maven_artifact:
    group_id: fi.tietoallas.integration.incremental
    artifact_id: ca-incremental
    version: "{{ ca_version }}"
    repository_url: "{{ maven_repository }}"
    username: "{{ datalake_maven_username }}"
    password: "{{ datalake_maven_password }}"
    dest: "{{ comp_dir }}/{{ ca_jar_name }}"
  notify: Restart ca

- name: Copy systemd start scirpt
  template:
    src: ca.service.j2
    dest: /etc/systemd/system/ca.service
    owner: root
    group: root
    mode: 0644
  notify: Restart ca

- name: Add Kafka topic
  command: /opt/DataLake/kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 2 --partitions 1 --topic ca
  ignore_errors: yes

- name: Reload systemd configs
  command: systemctl daemon-reload
